name: Playwright Tests
on:
  push:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Playwright Browsers
        run: yarn && yarn playwright install chromium --with-deps
      - name: Check Node version
        run: node --version
      - name: Run Playwright tests
        run: yarn playwright test --max-failures=5
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 30
